#!/usr/bin/env python
''' Command Line Interface for word_count '''
import argparse
from phds.cli import word_count

if __name__ == "__main__":

    # Parser
    parser = argparse.ArgumentParser(description="Counts the number of words \
                                                  in a text file")

    parser.add_argument('-i', required=True, type=str,
                        help='Input text file')

    args = parser.parse_args()

    word_count.word_count(args.i)
